@startuml

(*) --> "Wow Off"
If "true" then
--> [Yes] "(IMC_PPC_AVN_STATUS_04.MAIN_GEN_STS == 1 || FLCC_PPC_PMU_CAM_GUIDED_OFFSET_STATUS.MGEN_STATUS == 1) 
&& 
(IMC_PPC_AVN_STATUS_04.ST_GEN_STS == 1  || FLCC_PPC_PMU_CAM_GUIDED_OFFSET_STATUS.SGEN_STATUS == 1 )"
else
--> [NO]"FLCC_PPC_IPCMU_STATUS_1.NP >= 95 
&&
FLCC_PPC_IPCMU_STATUS_1.ENG_RUNNING == 1"
Endif
--> [Yes] "(IMC_PPC_AVN_STATUS_04.MAIN_GEN_STS == 1 || FLCC_PPC_PMU_CAM_GUIDED_OFFSET_STATUS.MGEN_STATUS == 1) 
&& 
(IMC_PPC_AVN_STATUS_04.ST_GEN_STS == 1  || FLCC_PPC_PMU_CAM_GUIDED_OFFSET_STATUS.SGEN_STATUS == 1 )"
-->"상단 오류 도시"
-->(*)

@enduml